version: '3.8'

services:
  postgres:
    container_name: db-asMoney

    restart: always

    image: postgres:latest

    ports:
      - '5432:5432'

    environment:
      POSTGRES_DB : db_as_money
      POSTGRES_USER : admin
      POSTGRES_PASSWORD : docker